# Change these first
owner: 8select # Your GitHub organization or username, where this repository lives
repo: status.8select.io # The name of this repository

sites:
  - name: 8select Website
    url: https://www.8select.com
  - name: 8select Admin Panel
    url: https://app.8select.io/
  - name: 8select GraphQL API
    url: https://api.8select.io/graphql
    mehtod: POST
    headers:
      - 'Content-Type: application/json'
      - 'X-Api-Id: 353227dc-f5d2-4bc9-9910-2402e2b91180'
    body: 'query { product(id: "8S-Dress-1-black") { productSets(first: 1) { edges { node { id } } } } }'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.8select.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 8select Status Page
  introTitle: '**8select** - HUMAN SELLING SKILLS ONLINE'
  introMessage: Our statuspage provides real-time information about the status and uptime of our services. We are committed to transparency and keeping you informed.
  navbar:
    - title: Status
      href: /
    - title: 8select
      href: https://www.8select.com/
    - title: 8select Docs
      href: https://docs.8select.io/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
